deployment:
  tasks:
    - export DEPLOYPATH=/home/<cpanel_username>/public_html
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R Build TemplateData index.html $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH